# Generated by Django 4.2.2 on 2023-07-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0006_fueling_station_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_Change_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inital_price', models.BigIntegerField()),
                ('new_price', models.BigIntegerField()),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.fueling_station')),
            ],
        ),
    ]
