# Generated by Django 4.2 on 2023-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_fuel_station_price_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_station_price',
            name='amount',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
