# Generated by Django 4.2 on 2023-06-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_fuel_station_price_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueling_station',
            name='local_goverment',
            field=models.CharField(default='Kuje', max_length=50),
            preserve_default=False,
        ),
    ]
