# Generated by Django 4.2 on 2023-06-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_fueling_station_local_goverment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueling_station',
            old_name='local_goverment',
            new_name='local_government',
        ),
    ]
