# Generated by Django 4.2.2 on 2023-07-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_rename_local_goverment_fueling_station_local_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueling_station',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fueling_station',
            name='opening_hours',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fueling_station',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='FuelStationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('date_time_commented', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.fueling_station')),
            ],
        ),
    ]
