# Generated by Django 4.2.2 on 2023-07-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_fueling_station_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_on_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50)),
                ('station_logo', models.ImageField(upload_to='logo')),
                ('station_background', models.ImageField(upload_to='background')),
            ],
        ),
        migrations.RemoveField(
            model_name='fueling_station',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='fueling_station',
            name='logo',
        ),
        migrations.AddField(
            model_name='fueling_station',
            name='background_image_url',
            field=models.CharField(default='rii', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fueling_station',
            name='logo_url',
            field=models.CharField(default='hhdhd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fueling_station',
            name='name',
            field=models.CharField(help_text='name of fueling station', max_length=50, verbose_name='Fueling Station Name'),
        ),
    ]
