# Generated by Django 4.2.2 on 2023-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_images_on_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueling_station',
            name='background_image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fueling_station',
            name='logo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
