# Generated by Django 4.2.2 on 2023-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_fueling_station_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueling_station',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='fueling_station',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='fueling_station',
            name='contact_information',
            field=models.CharField(help_text='Please provide a valid phone number of the fuel station attendant', max_length=50, null=True),
        ),
    ]
